name: OWASP ZAP Scan

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 1 * * *' # Runs every day at 01:00.

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Run ZAP Scan
      uses: zaproxy/action-baseline@v0.4.0
      with:
        target: 'http://testphp.vulnweb.com' # Replace with your website
        
